# Generated by Django 5.1.4 on 2025-01-10 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="opportunity_id",
            field=models.CharField(
                help_text="Business opportunity identifier", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["opportunity_id"], name="projects_pr_opportu_8513cd_idx"
            ),
        ),
    ]
