# Generated by Django 5.1.4 on 2025-01-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_opportunity_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="product_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional subcategory classification for this project",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.productsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                blank=True,
                help_text="Type of project (optional)",
                max_length=100,
                null=True,
            ),
        ),
    ]
