# Generated by Django 5.1.4 on 2025-01-22 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_product_subcategory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTeamLeaderHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tl_assignment_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_team_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_tl_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_team_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_tl_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leader_history",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Team Leader History",
                "verbose_name_plural": "Project Team Leader Histories",
                "ordering": ["-changed_at"],
            },
        ),
    ]
