# Generated by Django 5.1.4 on 2025-01-24 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectteamleaderhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tl_rating_comments",
            field=models.TextField(
                blank=True, help_text="Comments about the Team Leader's performance"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tl_rating_date",
            field=models.DateTimeField(
                blank=True, help_text="When the TL rating was last updated", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tl_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rating given by DPM to Team Leader (0-5)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
