# Generated by Django 5.1.4 on 2025-01-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_tl_rating_comments_project_tl_rating_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hs_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Human-readable unique identifier (e.g., A1, A2, B1, etc.)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
