# Generated by Django 5.1.4 on 2025-01-31 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_delivery_performance_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttask",
            name="quality_label",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_incharge",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member assigned as project incharge",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incharge_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="QualityLabel",
        ),
    ]
