# Generated by Django 5.2.1 on 2025-05-27 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_convert_hours_to_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="completion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When this assignment was marked as completed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="Whether this assignment is completed"
            ),
        ),
        migrations.CreateModel(
            name="ActiveTimer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When the timer was started"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The assignment being timed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.taskassignment",
                    ),
                ),
                (
                    "team_member",
                    models.OneToOneField(
                        help_text="Team member with active timer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Timer",
                "verbose_name_plural": "Active Timers",
            },
        ),
        migrations.CreateModel(
            name="TimerActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("START", "Start Timer"),
                            ("STOP", "Stop Timer"),
                            ("MANUAL_ADD", "Manual Time Added"),
                            ("EDIT_TOTAL", "Edited Daily Total"),
                            ("COMPLETE", "Task Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Additional details about this action"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The assignment this action relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.taskassignment",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        help_text="Team member who performed this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timer Action Log",
                "verbose_name_plural": "Timer Action Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TimeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When this work session started"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="When this work session ended", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of this session in minutes",
                        null=True,
                    ),
                ),
                (
                    "date_worked",
                    models.DateField(help_text="The date this work was performed"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of work done"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("TIMER", "Timer Session"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        default="TIMER",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The assignment this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_sessions",
                        to="projects.taskassignment",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        help_text="Team member who worked this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Session",
                "verbose_name_plural": "Time Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyTimeTotal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_worked",
                    models.DateField(help_text="The date this total represents"),
                ),
                (
                    "total_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total minutes worked on this assignment on this date",
                    ),
                ),
                (
                    "is_manually_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this total was manually adjusted by team member",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The assignment this total belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_totals",
                        to="projects.taskassignment",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        help_text="Team member who worked on this assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Time Total",
                "verbose_name_plural": "Daily Time Totals",
                "ordering": ["-date_worked"],
                "unique_together": {("assignment", "team_member", "date_worked")},
            },
        ),
    ]
