# Generated by Django 5.2.1 on 2025-05-27 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_taskassignment_completion_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRoster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Date for this roster entry")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LEAVE", "Leave"),
                            ("SICK_LEAVE", "Sick Leave"),
                            ("WEEK_OFF", "Week Off"),
                            ("HOLIDAY", "Holiday"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        default="PRESENT",
                        help_text="Working status for this date",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total assignment hours worked (auto-calculated from DailyTimeTotal)",
                    ),
                ),
                (
                    "misc_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Miscellaneous hours worked (manual entry)"
                    ),
                ),
                (
                    "misc_description",
                    models.CharField(
                        blank=True,
                        help_text="Description of miscellaneous work",
                        max_length=200,
                    ),
                ),
                (
                    "is_auto_created",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this entry was auto-created or manually edited",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes for this day"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        help_text="Team member this roster entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_rosters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Roster",
                "verbose_name_plural": "Daily Rosters",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["team_member", "date"],
                        name="projects_da_team_me_701394_idx",
                    ),
                    models.Index(
                        fields=["date", "status"], name="projects_da_date_fe020e_idx"
                    ),
                ],
                "unique_together": {("team_member", "date")},
            },
        ),
    ]
