# Generated by Django 5.2.1 on 2025-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_dailyroster_status_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeractionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("START", "Start Timer"),
                    ("STOP", "Stop Timer"),
                    ("MANUAL_ADD", "Manual Time Added"),
                    ("EDIT_SESSION", "Edited Session Duration"),
                    ("COMPLETE", "Task Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
