# Generated by Django 5.2.1 on 2025-05-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_timeractionlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesession",
            name="is_edited",
            field=models.BooleanField(
                default=False,
                help_text="Whether this session duration was manually edited",
            ),
        ),
    ]
