# Generated by Django 5.0.7 on 2025-06-02 00:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_timesession_is_edited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("TEAM_MEMBER", "Team Member"),
                            ("TEAM", "Team"),
                            ("PROJECT", "Project"),
                            ("ORGANIZATION", "Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        help_text="ID of team_member, project, etc. Null for organization-wide",
                        null=True,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "metrics_data",
                    models.JSONField(
                        default=dict, help_text="Stores all calculated metrics as JSON"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["metric_type", "entity_id", "period_start"],
                        name="projects_ag_metric__3b2d5b_idx",
                    ),
                    models.Index(
                        fields=["period_type", "period_start"],
                        name="projects_ag_period__171f6d_idx",
                    ),
                ],
                "unique_together": {
                    ("metric_type", "entity_id", "period_type", "period_start")
                },
            },
        ),
        migrations.CreateModel(
            name="ProjectDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="Date when project reached final delivery status"
                    ),
                ),
                (
                    "delivery_performance_rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Performance rating given to project incharge",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("hs_id", models.CharField(max_length=10)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField()),
                (
                    "days_variance",
                    models.IntegerField(
                        help_text="Negative means delivered early, positive means late"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="projects.project",
                    ),
                ),
                (
                    "project_incharge",
                    models.ForeignKey(
                        help_text="The project incharge at time of delivery",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_incharge", "delivery_date"],
                        name="projects_pr_project_aa2830_idx",
                    ),
                    models.Index(
                        fields=["delivery_date"], name="projects_pr_deliver_c4a196_idx"
                    ),
                ],
                "unique_together": {("project", "delivery_date")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "delivery_performance_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("is_final_delivery", models.BooleanField(default=False)),
                ("tasks_total", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="projects.project",
                    ),
                ),
                (
                    "project_incharge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incharge_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "date"],
                        name="projects_pr_project_d32117_idx",
                    ),
                    models.Index(
                        fields=["date", "is_final_delivery"],
                        name="projects_pr_date_8062ca_idx",
                    ),
                ],
                "unique_together": {("project", "date")},
            },
        ),
        migrations.CreateModel(
            name="TeamMemberMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The date these metrics represent"),
                ),
                ("total_projected_minutes", models.PositiveIntegerField(default=0)),
                ("total_worked_minutes", models.PositiveIntegerField(default=0)),
                (
                    "productivity_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Projected/Worked ratio as percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "available_minutes",
                    models.PositiveIntegerField(
                        default=480, help_text="Total available minutes for the day"
                    ),
                ),
                (
                    "utilization_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Worked/Available ratio as percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("assignments_completed", models.PositiveIntegerField(default=0)),
                (
                    "total_quality_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "average_quality_rating",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "projects_delivered",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of projects delivered on this date where user was incharge",
                    ),
                ),
                (
                    "total_delivery_rating_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of delivery performance ratings",
                        max_digits=6,
                    ),
                ),
                (
                    "average_delivery_rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average delivery performance rating as project incharge",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team_member", "date"],
                        name="projects_te_team_me_8fc2b2_idx",
                    ),
                    models.Index(fields=["date"], name="projects_te_date_f2e372_idx"),
                ],
                "unique_together": {("team_member", "date")},
            },
        ),
    ]
