# Generated by Django 5.0.7 on 2025-06-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_aggregatedmetrics_projectdelivery_projectmetrics_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyroster",
            name="assignment_hours",
        ),
        migrations.RemoveField(
            model_name="projectdelivery",
            name="days_variance",
        ),
    ]
