# Generated by Django 5.0.7 on 2025-06-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_remove_assignment_hours_from_roster"),
    ]

    operations = [
        # Remove the unnecessary metric models
        # These are being replaced with on-demand calculations
        
        migrations.DeleteModel(
            name='TeamMemberMetrics',
        ),
        
        migrations.DeleteModel(
            name='ProjectMetrics',
        ),
        
        migrations.DeleteModel(
            name='AggregatedMetrics',
        ),
        
        # NOTE: We're keeping ProjectDelivery as it's useful for historical tracking
        # of delivery events and performance ratings
    ]
