# Generated by Django 5.1.4 on 2025-06-15 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_auto_20250614_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdelivery",
            name="days_variance_snapshot",
            field=models.IntegerField(
                blank=True,
                help_text="Snapshot of days variance at time of delivery",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectstatushistory",
            name="changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp of the status change",
            ),
        ),
    ]
