# Generated by Django 5.1.3 on 2025-06-22 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_projectdelivery_days_variance_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdelivery",
            name="delivery_performance_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Delivery performance rating (1-5)",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
