# Generated by Django 5.0.7 on 2025-06-24 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_alter_projectdelivery_delivery_performance_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyroster",
            name="misc_description",
            field=models.CharField(
                blank=True,
                help_text="Description of miscellaneous work - DEPRECATED: Use MiscHours model instead",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailyroster",
            name="misc_hours",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Miscellaneous hours worked (manual entry) - DEPRECATED: Use MiscHours model instead",
            ),
        ),
        migrations.CreateModel(
            name="MiscHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when the misc work was performed"),
                ),
                (
                    "activity",
                    models.CharField(
                        help_text="Description of the misc activity", max_length=200
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Duration of the misc work in minutes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        help_text="Team member who worked these misc hours",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc_hours_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Misc Hours Entry",
                "verbose_name_plural": "Misc Hours Entries",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team_member", "date"],
                        name="projects_mi_team_me_bcc067_idx",
                    ),
                    models.Index(fields=["date"], name="projects_mi_date_8cae97_idx"),
                ],
            },
        ),
    ]
