# Generated by Django 5.0.7 on 2025-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_add_misc_hours_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="mischours",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR_ACTIVITY", "HR Activity(Organization)"),
                    ("TRAINING", "Training"),
                    ("RND", "R&D"),
                    ("TECHNICAL_ISSUE", "Technical Issue(Software & Internet)"),
                    ("TEAM_ACTIVITY", "Team Activity"),
                    ("REA_UNIVERSITY", "REA University"),
                    ("TASK_ISSUE", "Task Issue"),
                    ("INTERNAL_WORK", "Internal Work"),
                ],
                help_text="Category of the misc activity",
                max_length=20,
                null=True,
            ),
        ),
    ]
