# Generated by Django 5.0.7 on 2025-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_add_activity_type_to_misc_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesession",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FORGOT_TIMER", "Forgot to start timer"),
                    ("LATE_ASSIGNMENT", "Received late assignment"),
                    ("TIMER_ISSUE", "Timer technical issue"),
                    ("OFFLINE_WORK", "Work done offline"),
                ],
                help_text="Reason for manual time entry",
                max_length=20,
                null=True,
            ),
        ),
    ]
