# Generated by Django 5.1.4 on 2025-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_timesession_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="quality_rating_comments",
            field=models.TextField(
                blank=True,
                help_text="Optional comments about the quality of this assignment",
            ),
        ),
    ]
