# Generated by Django 5.0.7 on 2025-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_add_quality_rating_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstatusoption",
            name="bucket",
            field=models.CharField(
                default="Client",
                help_text="Bucket categorization for this status (e.g., 'Client', 'Internal')",
                max_length=100,
            ),
        ),
    ]
