# Generated by Django 5.2.1 on 2025-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("DPM", "Project Manager"), ("TEAM_MEMBER", "Team Member")],
                max_length=20,
            ),
        ),
    ]
