# Generated by Django 5.0.7 on 2025-07-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DPM", "Project Manager"),
                    ("TEAM_MEMBER", "Team Member"),
                    ("VIDEO_PM", "Video Production Manager"),
                ],
                max_length=20,
            ),
        ),
    ]
