# Generated by Django 5.0.7 on 2025-09-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_video_pm_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DPM", "Project Manager"),
                    ("TEAM_MEMBER", "Team Member"),
                    ("VIDEO_PM", "Video Production Manager"),
                    ("SENIOR_MANAGER", "Senior Manager"),
                ],
                max_length=20,
            ),
        ),
    ]
