# Generated by Django 5.0.7 on 2025-08-26 09:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the video product",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "expected_tat",
                    models.PositiveIntegerField(
                        help_text="Default expected turnaround time in days for this video product",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this video product is available for new projects",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Product",
                "verbose_name_plural": "Video Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VideoProjectStatusOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the status (e.g., 'Sales Confirmation')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "category_one",
                    models.CharField(
                        help_text="First level categorization (e.g., 'Pre-Production')",
                        max_length=100,
                    ),
                ),
                (
                    "category_two",
                    models.CharField(
                        help_text="Second level categorization (e.g., 'Not Started')",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Sequence number for ordering statuses"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this status is currently available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Project Status Option",
                "verbose_name_plural": "Video Project Status Options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VideoProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hs_id",
                    models.CharField(
                        editable=False,
                        help_text="Human-readable unique identifier (e.g., VP_00001, VP_00002)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "opportunity_id",
                    models.CharField(
                        help_text="Business opportunity identifier", max_length=100
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of video project (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="Name of the video project", max_length=255
                    ),
                ),
                (
                    "builder_name",
                    models.CharField(
                        help_text="Name of the builder/client", max_length=255
                    ),
                ),
                (
                    "package_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional package identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of video products for this project"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        help_text="Date when the video project was purchased"
                    ),
                ),
                (
                    "sales_confirmation_date",
                    models.DateField(
                        help_text="Date when sales confirmation was received"
                    ),
                ),
                (
                    "expected_tat",
                    models.PositiveIntegerField(
                        help_text="Expected turnaround time in days (defaults to video product TAT but can be overridden)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "account_manager",
                    models.CharField(
                        help_text="Name of the account manager responsible for this video project",
                        max_length=255,
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date of video project completion",
                        null=True,
                    ),
                ),
                (
                    "delivery_performance_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Delivery performance rating (1-5)",
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City where this video project is located",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_projects",
                        to="locations.city",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The video product being delivered in this project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_projects",
                        to="video_production.videoproduct",
                    ),
                ),
                (
                    "project_incharge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team member assigned as video project incharge",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_incharge_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_pm",
                    models.ForeignKey(
                        help_text="The Video Production Manager assigned to this project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_pm_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_status",
                    models.ForeignKey(
                        help_text="Current status of the video project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_projects",
                        to="video_production.videoprojectstatusoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Project",
                "verbose_name_plural": "Video Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProjectStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_one_snapshot",
                    models.CharField(
                        help_text="Category one value when this status was set",
                        max_length=100,
                    ),
                ),
                (
                    "category_two_snapshot",
                    models.CharField(
                        help_text="Category two value when this status was set",
                        max_length=100,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of the status change",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Optional comments about why the status was changed",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="The VIDEO_PM who made this status change",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The video project whose status changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="video_production.videoproject",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="The status that was set",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="video_production.videoprojectstatusoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Project Status History",
                "verbose_name_plural": "Video Project Status Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProjectDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="Date when video project reached final delivery status"
                    ),
                ),
                (
                    "delivery_performance_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Delivery performance rating (1-5)",
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("hs_id", models.CharField(max_length=10)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField()),
                (
                    "days_variance_snapshot",
                    models.IntegerField(
                        blank=True,
                        help_text="Snapshot of days variance at time of delivery",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="video_production.videoproject",
                    ),
                ),
                (
                    "project_incharge",
                    models.ForeignKey(
                        help_text="The project incharge at time of delivery",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_project_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Project Delivery",
                "verbose_name_plural": "Video Project Deliveries",
                "indexes": [
                    models.Index(
                        fields=["project_incharge", "delivery_date"],
                        name="video_produ_project_330c5b_idx",
                    ),
                    models.Index(
                        fields=["delivery_date"], name="video_produ_deliver_962941_idx"
                    ),
                ],
                "unique_together": {("project", "delivery_date")},
            },
        ),
        migrations.AddIndex(
            model_name="videoproject",
            index=models.Index(
                fields=["opportunity_id"], name="video_produ_opportu_d69ab6_idx"
            ),
        ),
    ]
