# Generated by Django 5.1.4 on 2025-06-29 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("typical_cut_rounds", models.PositiveIntegerField(default=3)),
                ("requires_voiceover", models.BooleanField(default=True)),
                ("expected_tat", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoProjectStatusOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales & Setup"),
                            ("PRE_PRODUCTION", "Pre-Production"),
                            ("PRODUCTION", "Production"),
                            ("POST_PRODUCTION", "Post-Production"),
                            ("CUTS", "Cut Iterations"),
                            ("VOICEOVER", "Voiceover"),
                            ("FINAL", "Final Delivery"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="SALES",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VideoProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hs_id", models.CharField(max_length=50, unique=True)),
                ("opportunity_id", models.CharField(max_length=100, unique=True)),
                ("project_name", models.CharField(max_length=255)),
                ("builder_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("production_vendor", models.CharField(max_length=255)),
                ("shoot_location", models.CharField(blank=True, max_length=255)),
                ("shoot_date", models.DateField(blank=True, null=True)),
                (
                    "video_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("purchase_date", models.DateField()),
                ("expected_completion_date", models.DateField()),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("current_cut_number", models.PositiveIntegerField(default=0)),
                ("max_cuts_allowed", models.PositiveIntegerField(default=7)),
                ("voiceover_required", models.BooleanField(default=True)),
                (
                    "voiceover_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("SCRIPT_SHARED", "Script Shared"),
                            ("SCRIPT_APPROVED", "Script Approved"),
                            ("COMPUTERIZED_VO", "Computerized VO"),
                            ("FINAL_RECORDING", "Final Recording"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locations.city"
                    ),
                ),
                (
                    "video_pm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_production.videoproduct",
                    ),
                ),
                (
                    "current_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_production.videoprojectstatusoption",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProjectDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_performance_rating",
                    models.CharField(
                        choices=[
                            ("ON_TIME", "On Time"),
                            ("EARLY", "Early"),
                            ("DELAYED", "Delayed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("days_variance", models.IntegerField()),
                ("total_cuts_delivered", models.PositiveIntegerField()),
                ("voiceover_iterations", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="video_production.videoproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoProjectStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="video_production.videoproject",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_production.videoprojectstatusoption",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoCut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cut_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DELIVERED", "Delivered"),
                            ("REWORK_REQUESTED", "Rework Requested"),
                            ("REWORK_IN_PROGRESS", "Rework In Progress"),
                            ("APPROVED", "Approved"),
                        ],
                        default="DELIVERED",
                        max_length=20,
                    ),
                ),
                ("delivered_date", models.DateTimeField(auto_now_add=True)),
                ("feedback_received_date", models.DateTimeField(blank=True, null=True)),
                ("rework_required", models.BooleanField(default=False)),
                ("client_feedback", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuts",
                        to="video_production.videoproject",
                    ),
                ),
            ],
            options={
                "ordering": ["cut_number"],
                "unique_together": {("project", "cut_number")},
            },
        ),
        migrations.CreateModel(
            name="VoiceoverScript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("script_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SHARED", "Shared"),
                            ("APPROVED", "Approved"),
                            ("CHANGES_REQUESTED", "Changes Requested"),
                        ],
                        default="SHARED",
                        max_length=20,
                    ),
                ),
                ("script_content", models.TextField()),
                ("shared_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voiceover_scripts",
                        to="video_production.videoproject",
                    ),
                ),
            ],
            options={
                "ordering": ["script_version"],
                "unique_together": {("project", "script_version")},
            },
        ),
    ]
