# Generated by Django 5.0.7 on 2025-08-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_production", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videoprojectdelivery",
            name="video_produ_project_330c5b_idx",
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="project_incharge",
        ),
        migrations.RemoveField(
            model_name="videoprojectdelivery",
            name="project_incharge",
        ),
    ]
