# Generated by Django 5.0.7 on 2025-08-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_production", "0002_remove_project_incharge_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoproject",
            name="delivery_performance_rating",
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="expected_completion_date",
        ),
    ]
